{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: {{ .Values.certManager.issuer }}
    kind: {{ .Values.certManager.issuerKind }}
  dnsNames:
  - {{ .Values.domain }}
{{- end }}
