{{- if .Values.groups }}
{{- range .Values.groups }}
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  kanidmRef:
    name: {{ $.Release.Name }}
  {{- if .members }}
  members:
  {{- range .members }}
  - {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
